# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: sdl/postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./../pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  node-service:
    image: node-service
    depends_on:
      - db
      - adminer
    networks:
      - app-network
    env_file:
      - ../.env
  
networks:
  app-network:
    driver: bridge
    
